spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: spring_cloud_config_client
eureka:
  client:
    service-url: http://eureka-dev:7001/eureka
---
server:
  port: 6002
spring:
  profiles: test
  application:
    name: spring_cloud_config_client
eureka:
  client:
    service-url: http://eureka-test:7001/eureka