spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: spring_cloud_config_client
eureka:
  client:
    registerWithEureka: false #false 表示不想注册中心注册自己
    fetchRegistry: false       # false 表示自己端就是注册中心，我的职责就是i维护服务实例，不需要去检索服务
    service-url:
      defaultZone: http://eureka-dev:6001/eureka
---
server:
  port: 6002
spring:
  profiles: test
  application:
    name: spring_cloud_config_client
eureka:
  client:
    registerWithEureka: false #false 表示不想注册中心注册自己
    fetchRegistry: false       # false 表示自己端就是注册中心，我的职责就是i维护服务实例，不需要去检索服务
    service-url: 
      defaultZone: http://eureka-test:6002/eureka