spring:
  profiles:
    active: dev
---
server:
  port: 6001
spring:
  profiles: dev
  application:
    name: spring_cloud_config_client
eureka:
  client:
    service-url:
      defaultZone: http://eureka-dev:6001/eureka
---
server:
  port: 6002
spring:
  profiles: test
  application:
    name: spring_cloud_config_client
eureka:
  client:
    service-url: 
      defaultZone: http://eureka-test:6002/eureka